# Generated by Django 4.2.14 on 2024-07-27 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quanitity',
            new_name='quantity',
        ),
    ]
